from dataclasses import dataclass, field, InitVar
from typing import Dict, Optional, Tuple, Union

from .chaum_pedersen import ChaumPedersenProof
from .election_object_base import ElectionObjectBase

from .group import ElementModP, ElementModQ

from .logs import log_warning

from .types import BALLOT_ID, CONTEST_ID, GUARDIAN_ID, SELECTION_ID


@dataclass
class CiphertextCompensatedDecryptionSelection(ElectionObjectBase):
    """
    A compensated fragment of a Guardian's Partial Decryption of a selection generated by an available guardian
    """

    guardian_id: GUARDIAN_ID
    """
    The Available Guardian that this share belongs to
    """

    missing_guardian_id: GUARDIAN_ID
    """
    The Missing Guardian for whom this share is calculated on behalf of
    """

    description_hash: ElementModQ
    """
    The SelectionDescription hash
    """

    share: ElementModP
    """
    The Share of the decryption of a selection. `M_{i,l} in the spec`
    """

    recovery_key: ElementModP
    """
    The Recovery Public Key for the missing_guardian that corresponds to the available guardian's share of the secret
    """

    proof: ChaumPedersenProof
    """
    The Proof that the share was decrypted correctly
    """


ProofOrRecovery = Union[
    ChaumPedersenProof, Dict[GUARDIAN_ID, CiphertextCompensatedDecryptionSelection]
]


@dataclass
class CiphertextDecryptionSelection(ElectionObjectBase):
    """
    A Guardian's Partial Decryption of a selection
    """

    guardian_id: GUARDIAN_ID
    """
    The Available Guardian that this share belongs to
    """

    description_hash: ElementModQ
    """
    The SelectionDescription hash
    """

    share: ElementModP
    """
    The Share of the decryption of a selection. `M_i` in the spec
    """

    proof_or_recovery: InitVar[ProofOrRecovery]

    proof: Optional[ChaumPedersenProof] = field(init=False, default=None)
    """
    The Proof that the share was decrypted correctly, if the guardian
    was available for decryption
    """

    recovered_parts: Optional[
        Dict[GUARDIAN_ID, CiphertextCompensatedDecryptionSelection]
    ] = field(init=False, default=None)
    """
    the rovered parts of the dectyption provided by available guardians,
    if the guardian was missing from decryption
    """

    def __post_init__(self, proof_or_recovery: ProofOrRecovery) -> None:
        # When constructing the Decryption Selection
        # the value can either be a share generated by a guardian
        # or one generated by the available guardians on behalf
        # of a missing guardian.
        if isinstance(proof_or_recovery, ChaumPedersenProof):
            self.proof = proof_or_recovery
        elif isinstance(proof_or_recovery, Dict):
            self.recovered_parts = proof_or_recovery
        else:
            log_warning(f"decryption share cannot assign {proof_or_recovery}")


@dataclass
class CiphertextDecryptionContest(ElectionObjectBase):
    """
    A Guardian's Partial Decryption of a contest
    """

    guardian_id: GUARDIAN_ID
    """
    The Available Guardian that this share belongs to
    """

    description_hash: ElementModQ
    """
    The ContestDescription Hash
    """

    selections: Dict[SELECTION_ID, CiphertextDecryptionSelection]
    """
    the collection of decryption shares for this contest's selections
    """


@dataclass
class CiphertextCompensatedDecryptionContest(ElectionObjectBase):
    """
    A Guardian's Partial Decryption of a contest
    """

    guardian_id: GUARDIAN_ID
    """
    The Available Guardian that this share belongs to
    """

    missing_guardian_id: GUARDIAN_ID
    """
    The Missing Guardian for whom this share is calculated on behalf of
    """

    description_hash: ElementModQ
    """
    The ContestDescription Hash
    """

    selections: Dict[SELECTION_ID, CiphertextCompensatedDecryptionSelection]
    """
    the collection of decryption shares for this contest's selections
    """


@dataclass
class BallotDecryptionShare:
    """
    A Guardian's Partial Decryption Share of a specific ballot (e.g. of a spoiled ballot)
    """

    guardian_id: GUARDIAN_ID
    """
    The Available Guardian that this share belongs to
    """

    public_key: ElementModP
    """
    The election public key for the guardian
    """

    ballot_id: BALLOT_ID
    """
    The Ballot Id that this Decryption Share belongs to
    """

    contests: Dict[CONTEST_ID, CiphertextDecryptionContest]
    """
    The collection of all contests in the ballot
    """


@dataclass
class CompensatedBallotDecryptionShare:
    """
    """

    guardian_id: GUARDIAN_ID
    """
    The Available Guardian that this share belongs to
    """

    missing_guardian_id: GUARDIAN_ID
    """
    The Missing Guardian for whom this share is calculated on behalf of
    """

    public_key: ElementModP
    """
    The election public key for the guardian
    """

    ballot_id: BALLOT_ID
    """
    The Ballot Id that this Decryption Share belongs to
    """

    contests: Dict[CONTEST_ID, CiphertextCompensatedDecryptionContest]
    """
    The collection of all contests in the ballot
    """


# TODO: rename to TallyDecryptionShare
@dataclass
class DecryptionShare:
    """
    A Guardian's Partial Decryption Share of an election tally
    """

    guardian_id: GUARDIAN_ID
    """
    The Available Guardian that this share belongs to
    """

    public_key: ElementModP
    """
    The election public key for the guardian
    """

    contests: Dict[CONTEST_ID, CiphertextDecryptionContest]
    """
    The collection of decryption shares for all contests in the election
    """

    spoiled_ballots: Dict[BALLOT_ID, BallotDecryptionShare]
    """
    The collection of decryption shares for all spoiled ballots in the election
    """


@dataclass
class CompensatedDecryptionShare:
    """
    A Compensated Partial Decryption Share generated by 
    an available guardian on behalf of a missing guardian
    """

    guardian_id: GUARDIAN_ID
    """
    The Available Guardian that this share belongs to
    """

    missing_guardian_id: GUARDIAN_ID
    """
    The Missing Guardian for whom this share is calculated on behalf of
    """

    public_key: ElementModP
    """
    The election public key for the guardian
    """

    contests: Dict[CONTEST_ID, CiphertextCompensatedDecryptionContest]
    """
    The collection of decryption shares for all contests in the election
    """

    spoiled_ballots: Dict[BALLOT_ID, CompensatedBallotDecryptionShare]
    """
    The collection of decryption shares for all spoiled ballots in the election
    """


def get_tally_shares_for_selection(
    selection_id: str, shares: Dict[GUARDIAN_ID, DecryptionShare],
) -> Dict[GUARDIAN_ID, Tuple[ElementModP, CiphertextDecryptionSelection]]:
    """
    Get all of the cast shares for a specific selection
    """
    cast_shares: Dict[
        GUARDIAN_ID, Tuple[ElementModP, CiphertextDecryptionSelection]
    ] = {}
    for share in shares.values():
        for contest in share.contests.values():
            for selection in contest.selections.values():
                if selection.object_id == selection_id:
                    cast_shares[share.guardian_id] = (share.public_key, selection)

    return cast_shares


def get_spoiled_shares_for_selection(
    ballot_id: str, selection_id: str, shares: Dict[GUARDIAN_ID, DecryptionShare],
) -> Dict[GUARDIAN_ID, Tuple[ElementModP, CiphertextDecryptionSelection]]:
    """
    Get the spoiled shares for a given selection
    """
    spoiled_shares: Dict[
        GUARDIAN_ID, Tuple[ElementModP, CiphertextDecryptionSelection]
    ] = {}
    for share in shares.values():
        for ballot in share.spoiled_ballots.values():
            if ballot.ballot_id == ballot_id:
                for contest in ballot.contests.values():
                    for selection in contest.selections.values():
                        if selection.object_id == selection_id:
                            spoiled_shares[share.guardian_id] = (
                                share.public_key,
                                selection,
                            )
    return spoiled_shares
