blank_issues_enabled: true
contact_links:
  - name: Discussions
    url: https://github.com/microsoft/electionguard/discussions
    about: Discuss suggestions and new features here.
  - name: Microsoft Security Response Center
    url: mailto:secure@microsoft.com
    about: Please report security vulnerabilities here.
  - name: ElectionGuard Team
    url: mailto:electionguard@microsoft.com
    about: Email the ElectionGuard team